export const PRICE_PER_ARMOR = 1.75;
export const PRICE_PER_DEXTERITY = PRICE_PER_ARMOR / 2;

export const PRICE_PER_DAMAGE_ROLL = 0.5;
export const PRICE_PER_DAMAGE = 1;
export const PRICE_PER_STRENGTH = PRICE_PER_DAMAGE / 2;

export const PRICE_PER_HP = 1;
export const PRICE_PER_ENDURANCE = PRICE_PER_HP * 2;
export const PRICE_PER_HP_POINT = PRICE_PER_HP / 3;

export const PRICE_PER_MANA_POINT = 0.1;

export const PRICE_PER_MAGIC_DICE_BONUS = PRICE_PER_DAMAGE_ROLL;
export const PRICE_PER_MAGIC_BONUS = PRICE_PER_DAMAGE;
export const PRICE_PER_INTELLIGENCE = PRICE_PER_MAGIC_BONUS / 2;

export const PRICE_PER_HP_REPLEN = PRICE_PER_HP * 60;
export const PRICE_PER_MP_REPLEN = PRICE_PER_HP * 60;
